name: .NET MAUI CI – GroceryApp (Android + Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workloads
      run: |
        dotnet workload install maui
        dotnet workload install maui-android
        dotnet workload install maui-windows

    - name: Restore
      run: dotnet restore Grocery.App/Grocery.App.csproj

    # -------- ANDROID --------
    - name: Build Android
      run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-android

    - name: Publish Android (APK)
      run: dotnet publish Grocery.App/Grocery.App.csproj -c Release -f net8.0-android -o ./artifacts/android

    - name: Upload Android artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: GroceryApp-Android-APK
        path: artifacts/android/**/*.apk
        if-no-files-found: error
        retention-days: 7

    # -------- WINDOWS --------
    - name: Build Windows
      run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win-x64

    - name: Publish Windows (WinUI)
      run: dotnet publish Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win-x64 --self-contained false -o ./artifacts/winui

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: GroceryApp-Windows
        path: artifacts/winui/**
        if-no-files-found: error
        retention-days: 7